"use client";
import { useQuery } from "@tanstack/react-query";
import { backtestCapabilitiesQuery, dashboardQuery } from "@/lib/api/queries";
import { StatusBadge } from "@/components/ui/badge";
import { formatDateTime, formatMoney } from "@/lib/utils";

function LoadState({loading,error}:{loading:boolean;error:boolean}){if(loading)return <div className="panel p-8 text-sm text-slate-500">Chargement…</div>;if(error)return <div className="panel p-8 text-sm text-rose-300">Données backend indisponibles.</div>;return null}
function Header({title,subtitle}:{title:string;subtitle:string}){return <div><h1 className="text-2xl font-semibold">{title}</h1><p className="mt-1 text-sm text-slate-500">{subtitle}</p></div>}
const th="px-4 py-3 text-left text-[10px] font-semibold uppercase tracking-wider text-slate-500";
const td="px-4 py-3 text-xs text-slate-300";

export function OpportunitiesWorkspace(){const q=useQuery({queryKey:["dashboard"],queryFn:dashboardQuery,refetchInterval:3000});if(q.isLoading||q.isError)return <LoadState loading={q.isLoading} error={q.isError}/>;const d=q.data!;return <div className="space-y-4"><Header title="Opportunités" subtitle="CandidateOpportunity détectées par le Scanner et décisions associées."/><section className="panel overflow-x-auto"><table className="w-full min-w-[900px]"><thead><tr><th className={th}>Date</th><th className={th}>System</th><th className={th}>Symbol</th><th className={th}>TF</th><th className={th}>Scanner</th><th className={th}>Triggers</th><th className={th}>AI</th><th className={th}>Risk</th></tr></thead><tbody>{d.opportunities.slice().reverse().map(o=>{const decision=d.decisions.find(x=>x.opportunity_id===o.opportunity_id);return <tr className="border-t border-slate-900" key={`${o.system_id}-${o.opportunity_id}`}><td className={td}>{o.created_at?formatDateTime(o.created_at):"—"}</td><td className={td}>{o.system_id}</td><td className={td}>{o.symbol}</td><td className={td}>{o.timeframe}</td><td className={td}>{o.priority_score??"—"}</td><td className={`${td} max-w-[300px] truncate`}>{o.triggers.join(", ")||"—"}</td><td className={td}><StatusBadge value={decision?.professor?.direction??decision?.branch_status??"NO_ANALYSIS"}/></td><td className={td}>{decision?.risk?<StatusBadge value={decision.risk.status}/>:"—"}</td></tr>})}</tbody></table>{d.opportunities.length===0&&<p className="p-8 text-sm text-slate-500">Aucune opportunité observable dans le snapshot actuel.</p>}</section></div>}

export function OrdersWorkspace(){const q=useQuery({queryKey:["dashboard"],queryFn:dashboardQuery,refetchInterval:3000});if(q.isLoading||q.isError)return <LoadState loading={q.isLoading} error={q.isError}/>;const orders=q.data!.systems.flatMap(s=>s.orders);return <div className="space-y-4"><Header title="Ordres" subtitle="Ordres exposés par le backend PAPER/SHADOW actuel. Aucun ordre LIVE n’est créé par cette vue."/><section className="panel overflow-x-auto"><table className="w-full min-w-[1000px]"><thead><tr>{["Client ID","System","Mode","Symbol","Side","Type","Quantity","Fill","Status","Submitted"].map(x=><th key={x} className={th}>{x}</th>)}</tr></thead><tbody>{orders.slice().reverse().map(o=><tr key={o.broker_order_id} className="border-t border-slate-900"><td className={`${td} font-mono`}>{o.client_order_id}</td><td className={td}>{o.system_id}</td><td className={td}>{o.provenance??"PAPER"}</td><td className={td}>{o.symbol}</td><td className={td}><StatusBadge value={o.side}/></td><td className={td}>{o.order_type}</td><td className={td}>{o.requested_quantity}</td><td className={td}>{o.average_fill_price??"—"}</td><td className={td}><StatusBadge value={o.status}/></td><td className={td}>{formatDateTime(o.created_at)}</td></tr>)}</tbody></table>{orders.length===0&&<p className="p-8 text-sm text-slate-500">Aucun ordre fourni par le backend.</p>}</section></div>}

export function PositionsWorkspace(){const q=useQuery({queryKey:["dashboard"],queryFn:dashboardQuery,refetchInterval:3000});if(q.isLoading||q.isError)return <LoadState loading={q.isLoading} error={q.isError}/>;const positions=q.data!.systems.flatMap(s=>s.positions);return <div className="space-y-4"><Header title="Positions" subtitle="Positions backend. Mark courant, stop/target et PnL non réalisé restent indisponibles s’ils ne sont pas fournis par le contrat courant."/><section className="panel overflow-x-auto"><table className="w-full min-w-[850px]"><thead><tr>{["System","Mode","Symbol","Side","Quantity","Average entry","Realized PnL","Current mark","Unrealized PnL"].map(x=><th key={x} className={th}>{x}</th>)}</tr></thead><tbody>{positions.map((p,i)=><tr key={`${p.system_id}-${p.symbol}-${i}`} className="border-t border-slate-900"><td className={td}>{p.system_id}</td><td className={td}>{p.provenance??"PAPER"}</td><td className={td}>{p.symbol}</td><td className={td}><StatusBadge value={p.side??"UNKNOWN"}/></td><td className={td}>{p.quantity}</td><td className={td}>{p.average_entry}</td><td className={td}>{p.realized_pnl}</td><td className={`${td} text-slate-600`}>Non fourni</td><td className={`${td} text-slate-600`}>Non fourni</td></tr>)}</tbody></table>{positions.length===0&&<p className="p-8 text-sm text-slate-500">Aucune position ouverte exposée par le backend.</p>}</section></div>}

export function HistoryWorkspace(){const q=useQuery({queryKey:["dashboard"],queryFn:dashboardQuery,refetchInterval:3000});if(q.isLoading||q.isError)return <LoadState loading={q.isLoading} error={q.isError}/>;return <div className="space-y-4"><Header title="Historique" subtitle="Journal transversal observable. L’origine et la provenance restent visibles; LIVE, PAPER, SHADOW et BACKTEST ne sont pas fusionnés implicitement."/><section className="panel divide-y divide-slate-900">{q.data!.events.slice().reverse().map(e=><div className="grid gap-3 p-4 text-xs md:grid-cols-[150px_100px_120px_1fr]" key={e.event_id}><span className="font-mono text-slate-500">{formatDateTime(e.created_at)}</span><StatusBadge value={e.severity}/><span className="text-slate-400">{e.kind}</span><span><span className="text-slate-200">{e.message??e.code??"Événement"}</span><span className="ml-2 text-slate-600">{e.system_id??"global"}</span></span></div>)}{q.data!.events.length===0&&<p className="p-8 text-sm text-slate-500">Aucun événement disponible.</p>}</section></div>}

export function AgentsWorkspace(){const registry=useQuery({queryKey:["backtest-capabilities"],queryFn:backtestCapabilitiesQuery});const dash=useQuery({queryKey:["dashboard"],queryFn:dashboardQuery,refetchInterval:5000});if(registry.isLoading||dash.isLoading||registry.isError||dash.isError)return <LoadState loading={registry.isLoading||dash.isLoading} error={registry.isError||dash.isError}/>;const costs=new Map<string,number>();dash.data!.systems.forEach(system=>Object.entries(system.ai_usage.by_agent_eur).forEach(([agent,cost])=>costs.set(agent,(costs.get(agent)??0)+Number(cost))));return <div className="space-y-4"><Header title="Agents" subtitle="Registry backend et observabilité de coût. La liste n’est pas codée en dur côté interface."/><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{registry.data!.agents.map(agent=><article className="panel p-4" key={agent.agent}><div className="flex items-center justify-between"><div><h2 className="capitalize font-semibold">{agent.agent}</h2><p className="text-xs text-slate-500">{agent.role}</p></div><StatusBadge value={agent.state}/></div><div className="mt-4 grid grid-cols-2 gap-3 text-xs"><div><p className="text-slate-600">Type</p><p>{agent.core?"CORE":"SPECIALIST"}</p></div><div><p className="text-slate-600">Coût observable</p><p>{formatMoney(costs.get(agent.agent)??null)}</p></div></div></article>)}</div></div>}

export function EvaluationWorkspace(){const q=useQuery({queryKey:["dashboard"],queryFn:dashboardQuery,refetchInterval:5000});if(q.isLoading||q.isError)return <LoadState loading={q.isLoading} error={q.isError}/>;return <div className="space-y-4"><Header title="Évaluation" subtitle="Métriques calculées par le backend Evaluation. Aucun KPI n’est recalculé ou inventé côté frontend."/>{q.data!.systems.map(system=><section className="panel p-5" key={system.system_id}><div className="flex items-center gap-2"><h2 className="font-semibold">{system.display_name}</h2><StatusBadge value={system.batch10.status}/></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(system.batch10.metrics).map(([key,metric])=><div className="rounded-lg border border-slate-800 bg-slate-950/60 p-3" key={key}><p className="text-[10px] uppercase tracking-wider text-slate-600">{metric.name??key}</p><p className="mt-2 font-mono text-sm">{metric.value??"Indisponible"} {metric.unit??""}</p>{metric.reason&&<p className="mt-1 text-[10px] text-slate-600">{metric.reason}</p>}</div>)}</div><div className="mt-4 text-xs text-slate-500">AI total: {formatMoney(system.ai_usage.total_cost_eur)} · records: {system.ai_usage.record_count}</div></section>)}</div>}
