"use client";
import { useQuery } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { EquityChart } from "@/components/chart/equity-chart";
import { TradingChart } from "@/components/chart/trading-chart";
import { StatusBadge } from "@/components/ui/badge";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { campaignConfigurationQuery, campaignProgressQuery, campaignQuery, replayQuery } from "@/lib/api/queries";
import type { BacktestReplay, CampaignConfiguration, CampaignProgress, CampaignSummary } from "@/lib/api/schemas";
import { formatDateTime } from "@/lib/utils";
import { ReplayControls } from "./replay-controls";
import { ReplayInspector } from "./replay-inspector";
import type { ReplaySpeed } from "./replay-state";

const roles=["DESIGN","VALIDATION","OOS"] as const;
export function BacktestDetail({campaignId}:{campaignId:string}){
 const progress=useQuery({queryKey:["campaign-progress",campaignId],queryFn:()=>campaignProgressQuery(campaignId),refetchInterval:q=>q.state.data?.result_available?false:1000,retry:false});
 const campaign=useQuery({queryKey:["campaign",campaignId],queryFn:()=>campaignQuery(campaignId),enabled:progress.data?.result_available===true||progress.isError,retry:false});
 const configuration=useQuery({queryKey:["campaign-configuration",campaignId],queryFn:()=>campaignConfigurationQuery(campaignId),enabled:campaign.isSuccess,retry:false});
 const [role,setRole]=useState<(typeof roles)[number]>("OOS");
 const replay=useQuery({queryKey:["replay",campaignId,role],queryFn:()=>replayQuery(campaignId,role),enabled:campaign.isSuccess,retry:false});
 const [index,setIndex]=useState(0); const [playing,setPlaying]=useState(false); const [speed,setSpeed]=useState<ReplaySpeed>(1);
 const traces=useMemo(()=>{const candle=replay.data?.candles[index];if(!candle)return [];const time=candle.time;return replay.data?.traces.filter(trace=>Math.floor(new Date(trace.observed_at).getTime()/1000)<=time).slice(-12)??[]},[replay.data,index]);
 const cursorTime=replay.data?.candles[index]?.time??null;
 const summary=campaign.data;
 if(progress.data && !progress.data.result_available && !campaign.data)return <ProgressView progress={progress.data}/>;
 return <div className="space-y-4">
  <div className="panel flex flex-wrap items-center gap-3 p-4"><div><p className="panel-title">Backtest campaign</p><h1 className="mt-1 font-mono text-lg">{campaignId}</h1></div><StatusBadge value={summary?.ai_mode??progress.data?.status??"UNKNOWN"}/><span className="ml-auto text-xs text-slate-500">{summary?formatDateTime(summary.created_at):""}</span></div>
  {summary&&<CampaignHeader campaign={summary}/>}
  {configuration.data&&<ConfigurationPanel configuration={configuration.data}/>} 
  <Tabs value={role} onValueChange={value=>{setRole(value as typeof role);setIndex(0);setPlaying(false)}}><TabsList className="w-fit">{roles.map(value=><TabsTrigger key={value} value={value}>{value}{value==="OOS"?" · OUT-OF-SAMPLE":""}</TabsTrigger>)}</TabsList></Tabs>
  {replay.isError?<div className="panel p-6"><p className="text-sm text-amber-200">Replay détaillé indisponible pour cette campagne.</p><p className="mt-2 text-xs leading-5 text-slate-500">Cette campagne ne possède pas les artefacts V2 nécessaires au replay détaillé. Les nouvelles campagnes V2 persistent désormais dataset, configuration, traces et exports côté backend.</p></div>:replay.isLoading?<div className="panel p-8 text-sm text-slate-500">Chargement du replay…</div>:replay.data&&<>
   <div className="grid min-h-[600px] gap-3 xl:grid-cols-[minmax(0,1fr)_360px]"><section className="panel overflow-hidden"><div className="flex items-center gap-2 border-b border-slate-800 px-4 py-3"><StatusBadge value="BACKTEST"/><span className="text-xs text-slate-400">{replay.data.symbol} · {replay.data.timeframe}</span><span className="ml-auto text-[10px] text-slate-600">Les événements sont rejoués; aucune décision n’est recalculée dans le navigateur.</span></div><div className="h-[520px]"><TradingChart mode="BACKTEST" symbol={replay.data.symbol} timeframe={replay.data.timeframe} candles={replay.data.candles.slice(0,index+1)} events={replay.data.events.filter(e=>Math.floor(new Date(e.observed_at).getTime()/1000)<=(cursorTime??0))} cursorTime={cursorTime} onEventSelect={(event)=>{const time=Math.floor(new Date(event.observed_at).getTime()/1000);const target=replay.data!.candles.findIndex(c=>c.time>=time);setIndex(target<0?replay.data!.candles.length-1:target);setPlaying(false)}}/></div><ReplayControls replay={replay.data} index={index} setIndex={setIndex} playing={playing} setPlaying={setPlaying} speed={speed} setSpeed={setSpeed}/></section><aside className="panel overflow-auto"><ReplayInspector traces={traces}/></aside></div>
   <TradeAndEvents replay={replay.data} setIndex={(time)=>{const target=replay.data.candles.findIndex(c=>c.time>=time);setIndex(target<0?replay.data.candles.length-1:target);setPlaying(false)}}/>
   <section className="panel p-4"><p className="panel-title mb-3">Equity · {role}</p><EquityChart points={replay.data.equity}/></section>
  </>}
 </div>
}
function ProgressView({progress}:{progress:CampaignProgress}){return <div className="space-y-4"><div className="panel p-6"><div className="flex items-center gap-2"><StatusBadge value={progress.status}/><StatusBadge value={progress.phase}/></div><h1 className="mt-4 text-xl font-semibold">Historical Replay en cours</h1><p className="mt-2 text-sm text-slate-400">{progress.message}</p><div className="mt-5 h-2 overflow-hidden rounded bg-slate-900"><div className="h-full bg-violet-500" style={{width:`${progress.percent}%`}}/></div><div className="mt-3 flex flex-wrap gap-4 text-xs text-slate-500"><span>{progress.percent.toFixed(1)}%</span><span>{progress.opportunity_count} opportunités</span><span>{progress.executed_order_count} ordres PAPER</span><span>Agents: {progress.active_agents.join(", ")||"aucun actif"}</span></div></div></div>}
function CampaignHeader({campaign}:{campaign:CampaignSummary}){return <div className="grid gap-3 lg:grid-cols-4"><Card label="Dataset" value={`${campaign.dataset.dataset_id} · ${campaign.dataset.candle_count} bars`}/><Card label="DESIGN" value={`${campaign.design.trading_net.value??"—"} · DD ${campaign.design.max_drawdown_pct.value??"—"}`}/><Card label="VALIDATION" value={`${campaign.validation.trading_net.value??"—"} · ${campaign.validation.closed_trades} trades`}/><Card label="OOS · OUT-OF-SAMPLE" value={`${campaign.oos.trading_net.value??"—"} · ${campaign.oos.closed_trades} trades`}/></div>}
function Card({label,value}:{label:string;value:string}){return <div className="panel p-4"><p className="text-[10px] uppercase tracking-wider text-slate-600">{label}</p><p className="mt-2 text-sm font-medium text-slate-200">{value}</p></div>}
function TradeAndEvents({replay,setIndex}:{replay:BacktestReplay;setIndex:(time:number)=>void}){return <section className="panel overflow-hidden"><div className="grid gap-0 lg:grid-cols-2"><div className="max-h-[300px] overflow-auto border-b border-slate-800 lg:border-b-0 lg:border-r"><p className="panel-title sticky top-0 bg-slate-950 px-4 py-3">Trades</p>{replay.trades.length===0?<p className="p-4 text-xs text-slate-500">Aucun trade fermé sur cette période.</p>:replay.trades.map(trade=><button key={trade.trade_id} className="grid w-full grid-cols-[1fr_80px_90px] border-t border-slate-900 px-4 py-3 text-left text-xs hover:bg-slate-900/60" onClick={()=>setIndex(Math.floor(new Date(trade.opened_at).getTime()/1000))}><span><span className="font-mono">{trade.trade_id.slice(0,10)}</span><br/><span className="text-slate-500">{trade.side} · {trade.entry_price} → {trade.exit_price}</span></span><span>{trade.quantity}</span><span className={Number(trade.net_pnl)>=0?"text-emerald-300":"text-rose-300"}>{trade.net_pnl}</span></button>)}</div><div className="max-h-[300px] overflow-auto"><p className="panel-title sticky top-0 bg-slate-950 px-4 py-3">Events / Decision Trace</p>{replay.events.map(event=><button key={event.event_id} className="flex w-full items-center gap-3 border-t border-slate-900 px-4 py-2 text-left text-xs hover:bg-slate-900/60" onClick={()=>setIndex(Math.floor(new Date(event.observed_at).getTime()/1000))}><StatusBadge value={event.event_type}/><span className="truncate text-slate-400">{event.label}</span><span className="ml-auto font-mono text-[10px] text-slate-600">{new Date(event.observed_at).toISOString().slice(11,19)}</span></button>)}</div></div></section>}

function ConfigurationPanel({configuration}:{configuration:CampaignConfiguration}){return <details className="panel p-4"><summary className="cursor-pointer text-sm font-semibold text-slate-200">Configuration figée du run</summary><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Card label="System" value={configuration.system_id}/><Card label="Capital" value={configuration.execution.initial_balance}/><Card label="Risk / trade" value={`${(Number(configuration.risk.max_risk_per_trade_pct)*100).toFixed(2)}%`}/><Card label="AI" value={`${configuration.ai.mode} · ${configuration.ai.model_id}`}/><Card label="Walk-Forward" value={configuration.walk_forward.enabled?`ON · ${configuration.walk_forward.design_bars}/${configuration.walk_forward.validation_bars}/${configuration.walk_forward.oos_bars}`:"OFF"}/></div><div className="mt-3 grid gap-2 font-mono text-[10px] text-slate-500 md:grid-cols-2"><span>commit: {configuration.execution.code_version}</span><span>execution: {configuration.execution.execution_model_version}</span><span>dataset: {configuration.dataset_id}</span><span>budget IA: {configuration.ai.hard_budget_eur} €</span></div></details>}
